apiVersion: v1
kind: Pod
metadata:
  name: pv-test-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: nginx:1.27
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: local-storage
  volumes:
    - name: local-storage
      persistentVolumeClaim:
        claimName: local-pvc
